# Generated by Django 3.0.4 on 2020-05-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdata',
            name='competitionname',
            field=models.CharField(default='none', max_length=80),
            preserve_default=False,
        ),
    ]
